
@HotelListing.API_HostAddress = https://localhost:7146
@json = application/json
# @host = https://localhost:7124
@hotelId = 5
@bookingId = 17
@today = {{$localDatetime iso8601}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMjAzNzk2MS00OWY5LTQ5ZmEtYmQ3ZC1hNmJhNDY4OTEzNTkiLCJlbWFpbCI6InVzZXIxMTFAbG9jYWxob3N0LmNvbSIsImp0aSI6Ijc0MDIyNmZjLTc1ZWMtNGFmOC1iYzgxLTMzMzdhOGNkZmJhYiIsIm5hbWUiOiJEb2UsIEpvaG5ueSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NzQzNzM0NzcsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.wGbTUfFVSNLD65Q2NVRlIC3WlqXidGqhybOMbXtBg_M
@apiKey=dXNlcjZAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=

GET {{HotelListing.API_HostAddress}}/api/countries
Authorization: Bearer {{token}}
## X-Api-Key: {{apiKey}}
###

POST {{HotelListing.API_HostAddress}}/api/countries
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "Name": "Portugal",
  "ShortName": "POR"
}

###

@deleteCountryId=23
DELETE {{HotelListing.API_HostAddress}}/api/countries/{{deleteCountryId}}
Authorization: Bearer {{token}}

###

@getCountryId=14
GET {{HotelListing.API_HostAddress}}/api/countries/{{getCountryId}}
Authorization: Bearer {{token}}

###

@updateCountryId=14
PUT {{HotelListing.API_HostAddress}}/api/countries/{{updateCountryId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "Id": 14,
  "Name": "Netherlands",
  "ShortName": "NET"
}

###

GET {{HotelListing.API_HostAddress}}/api/hotels
Authorization: Bearer {{token}}
###

POST {{HotelListing.API_HostAddress}}/api/hotels
Authorization: Basic {{token}}
Content-Type: {{json}}

{
  "Name": "Hotel Westchester",
  "Address": "Victory Avenue",
  "Rating": 5,
  "CountryId": 15
}

###

@deleteHotelId=9
DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{deleteHotelId}}

###

@getHotelId=5
GET {{HotelListing.API_HostAddress}}/api/hotels/{{getHotelId}}
Authorization: Bearer {{token}}

###

@updateHotelId=5
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{updateHotelId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "id": 5,
  "name": "Hotel Worcester",
  "address": "Avenue 67",
  "rating": 5,
  "countryId": 15
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "admin2@localhost.com",
  "password": "P@ssword1",
  "firstName": "Johnny",
  "lastName": "Doe",
  "role": "Administrator"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: {{json}}
{
  "email": "admin2@localhost.com",
  "password": "P@ssword1"
}

###

POST {{HotelListing.Api_HostAddress}}/api/defaultauth/login
Content-Type: {{json}}

{
  "email": "user8@localhost.com",
  "password": "P@ssword1"
}

###

GET {{HotelListing.API_HostAddress}}/api/apikey
X-Api-Key: {{@apiKey}}

###

GET {{HotelListing.API_HostAddress}}/api/basicauth
Authorization: Basic {{apiKey}}

###



#### Bookings Testing ####

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "user111@localhost.com",
  "password": "P@ssword1",
  "firstName": "Johnny",
  "lastName": "Doe",
  "role": "User"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: {{json}}

{
  "email": "user111@localhost.com",
  "password": "P@ssword1"
}

###

### 1) CreateBookingDto - Creating the first booking
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-03-15",
  "checkOut": "2026-03-25",
  "guests": 5
}

###

### 2) CreateBookingDto - Creating another booking for a different hotel
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-04-10",
  "checkOut": "2026-04-15",
  "guests": 5
}

### 3) CreateBookingDto - Creating an invalid booking
### Expected Message: The selected dates overlap with an existing booking.
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-03-25",
  "checkOut": "2026-03-28",
  "guests": 1
}

###

### 4) CreateBookingDto - Creating an invalid booking
### Expected Message: The field Guests must be between 1 and 10.
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-03-01",
  "checkOut": "2026-03-05",
  "guests": 0
}

###

### 5) CreateBookingDto - Creating an invalid booking
### Expected Message: The field Guests must be between 1 and 10.
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-04-25",
  "checkOut": "2026-04-28",
  "guests": 11
}

###

### 6) UpdateBookingDto - Extending the stay period
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-20",
  "checkOut": "2026-03-30",
  "guests": 1
}

###

### 7) UpdateBookingDto - Reducing the stay period
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-21",
  "checkOut": "2026-03-29",
  "guests": 1
}

###

### 8) UpdateBookingDto - Modifying the number of guests
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-21",
  "checkOut": "2026-03-29",
  "guests": 5
}

###

### 9) UpdateBookingDto - Invalid number of guests
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-21",
  "checkOut": "2026-03-29",
  "guests": 12
}

###

### 10) UpdateBookingDto - Overlaping dates
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-25",
  "checkOut": "2026-03-31",
  "guests": 3
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "hoteladmin3@localhost.com",
  "password": "P@ssword1",
  "firstName": "Johnny",
  "lastName": "Doe",
  "role": "Hotel Admin",
  "associatedHotelId": 5
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: {{json}}

{
  "email": "hoteladmin3@localhost.com",
  "password": "P@ssword1"
}


### 11) Admin Confirm Booking
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}/admin/confirm
Authorization: Bearer {{token}}

###

### 12) Admin Cancel Booking
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}/admin/cancel
Authorization: Bearer {{token}}

###

### 13) User Cancel Booking
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}/cancel
Authorization: Bearer {{token}}

###

### 14) Listing all bookings for a specific hotel
GET {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
###


#### Pagination Features Testing ####

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "user111@localhost.com",
  "password": "P@ssword1",
  "firstName": "John",
  "lastName": "Doe",
  "role": "User"
}

### "associatedHotelId": 5

###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: {{json}}

{
  "email": "user111@localhost.com",
  "password": "P@ssword1"
}

### GetCountryHotels - Applying Rating and Price Filters

@paginationCountryId=84


### 1) MinRating greter than MaxRating

GET {{HotelListing.API_HostAddress}}/api/hotels?pageNumber=1&pageSize=100&minRating=5&maxRating=4&minPrice=100&maxPrice=150
Authorization: Bearer {{token}}

###

### 2) MinPrice greater than MaxPrice

GET {{HotelListing.API_HostAddress}}/api/hotels?pageNumber=1&pageSize=100&minRating=4&maxRating=5&minPrice=150&maxPrice=100
Authorization: Bearer {{token}}

###

### 3) No validation case

GET {{HotelListing.API_HostAddress}}/api/hotels?pageNumber=1&pageSize=100&minRating=4&maxRating=5&minPrice=100&maxPrice=150
Authorization: Bearer {{token}}

###
