@HotelListing.API_HostAddress = https://localhost:7146


GET {{HotelListing.API_HostAddress}}/api/countries

###

POST {{HotelListing.API_HostAddress}}/api/countries
Content-Type: application/json

{
  "Name": "Russia",
  "ShortName": "RUS"
}

###

@deleteCountryId=11
DELETE {{HotelListing.API_HostAddress}}/api/countries/{{deleteCountryId}}

###

@getCountryId=20
GET {{HotelListing.API_HostAddress}}/api/countries/{{getCountryId}}

###

@updateCountryId=20
PUT {{HotelListing.API_HostAddress}}/api/countries/{{updateCountryId}}
Content-Type: application/json

{
  "Id": 20,
  "Name": "Ukraine",
  "ShortName": "UKR"
}

###

GET {{HotelListing.API_HostAddress}}/api/hotels

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name": "Hotel Stalinskaya",
  "Address": "St. 003",
  "Rating": 1,
  "CountryId": 20
}

###

@deleteHotelId=9
DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{deleteHotelId}}

###

@getHotelId=9
GET {{HotelListing.API_HostAddress}}/api/hotels/{{getHotelId}}

###

@updateHotelId=9
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{updateHotelId}}
Content-Type: application/json

{
  "id": 9,
  "name": "Hotel Stalinskaya",
  "address": "St. 67",
  "rating": 5,
  "countryId": 20
}

###
