@HotelListing.API_HostAddress = https://localhost:7146
@json = application/json
# @host = https://localhost:7124
@hotelId = 5
@bookingId = 9
@today = {{$localDatetime iso8601}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Mjg0NTY5Yy03NGJkLTQ0NjktOTA2NS1kMjY5MzY3Y2Y3ZjciLCJlbWFpbCI6ImhvdGVsYWRtaW4zQGxvY2FsaG9zdC5jb20iLCJqdGkiOiJmNjk1N2ZjZi0yNjA1LTQ5YjctOTI5My05Y2I4N2Q1NjhiNjUiLCJuYW1lIjoiRG9lLCBKb2hubnkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJIb3RlbCBBZG1pbiIsImV4cCI6MTc3NDI4NzIxNCwiaXNzIjoiSG90ZWxMaXN0aW5nQVBJIiwiYXVkIjoiSG90ZWxMaXN0aW5nQVBJQ2xpZW50In0.NMtLwo2ju6x3ppxUz13pIpMt6dcNEl53DhZq-RzgHc8
@apiKey=dXNlcjZAbG9jYWxob3N0LmNvbTpQQHNzd29yZDE=

GET {{HotelListing.API_HostAddress}}/api/countries
Authorization: Bearer {{token}}
## X-Api-Key: {{apiKey}}
###

POST {{HotelListing.API_HostAddress}}/api/countries
Authorization: Bearer {{token}}
Content-Type: {{@json}}

{
  "Name": "Spain",
  "ShortName": "ESP"
}

###

@deleteCountryId=21
DELETE {{HotelListing.API_HostAddress}}/api/countries/{{deleteCountryId}}
Authorization: Bearer {{token}}

###

@getCountryId=13
GET {{HotelListing.API_HostAddress}}/api/countries/{{getCountryId}}
Authorization: Bearer {{token}}

###

@updateCountryId=13
PUT {{HotelListing.API_HostAddress}}/api/countries/{{updateCountryId}}
Authorization: Bearer {{token}}
Content-Type: {{@json}}

{
  "Id": 13,
  "Name": "Italy",
  "ShortName": "IT"
}

###

GET {{HotelListing.API_HostAddress}}/api/hotels
Authorization: Bearer {{token}}
###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: {{@json}}

{
  "Name": "Hotel Stalinskaya",
  "Address": "St. 003",
  "Rating": 1,
  "CountryId": 20
}

###

@deleteHotelId=9
DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{deleteHotelId}}

###

@getHotelId=5
GET {{HotelListing.API_HostAddress}}/api/hotels/{{getHotelId}}
Authorization: Bearer {{token}}

###

@updateHotelId=5
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{updateHotelId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "id": 5,
  "name": "Hotel Worcester",
  "address": "Avenue 67",
  "rating": 5,
  "countryId": 15
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "hoteladmin1@localhost.com",
  "password": "P@ssword1",
  "firstName": "Johnny",
  "lastName": "Doe",
  "role": "Hotel Admin"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: {{json}}
{
  "email": "admin1@localhost.com",
  "password": "P@ssword1"
}

###

POST {{HotelListing.Api_HostAddress}}/api/defaultauth/login
Content-Type: {{json}}

{
  "email": "user8@localhost.com",
  "password": "P@ssword1"
}

###

GET {{HotelListing.API_HostAddress}}/api/apikey
X-Api-Key: {{@apiKey}}

###

GET {{HotelListing.API_HostAddress}}/api/basicauth
Authorization: Basic {{apiKey}}

###



#### Bookings Testing ####

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "hoteladmin1@localhost.com",
  "password": "P@ssword1",
  "firstName": "Johnny",
  "lastName": "Doe",
  "role": "Hotel Admin"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: {{json}}

{
  "email": "hoteladmin1@localhost.com",
  "password": "P@ssword1"
}

###

### 1) CreateBookingDto - Creating the first booking
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-03-30",
  "checkOut": "2026-03-31",
  "guests": 1
}

###

### 2) CreateBookingDto - Creating another booking for a different hotel
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-03-23",
  "checkOut": "2026-03-28",
  "guests": 1
}

### 3) CreateBookingDto - Creating an invalid booking
### Expected Message: The selected dates overlap with an existing booking.
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-03-25",
  "checkOut": "2026-03-28",
  "guests": 1
}

###

### 4) CreateBookingDto - Creating an invalid booking
### Expected Message: The field Guests must be between 1 and 10.
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-04-25",
  "checkOut": "2026-04-28",
  "guests": 0
}

###

### 5) CreateBookingDto - Creating an invalid booking
### Expected Message: The field Guests must be between 1 and 10.
POST {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "hotelId": {{hotelId}},
  "checkIn": "2026-04-25",
  "checkOut": "2026-04-28",
  "guests": 11
}

###

### 6) UpdateBookingDto - Extending the stay period
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-20",
  "checkOut": "2026-03-28",
  "guests": 1
}

###

### 7) UpdateBookingDto - Reducing the stay period
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-30",
  "checkOut": "2026-03-31",
  "guests": 1
}

###

### 8) UpdateBookingDto - Modifying the number of guests
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-30",
  "checkOut": "2026-03-31",
  "guests": 5
}

###

### 9) UpdateBookingDto - Invalid number of guests
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-30",
  "checkOut": "2026-03-31",
  "guests": 20
}

###

### 10) UpdateBookingDto - Overlaping dates
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "checkIn": "2026-03-25",
  "checkOut": "2026-03-31",
  "guests": 3
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "hoteladmin3@localhost.com",
  "password": "P@ssword1",
  "firstName": "Johnny",
  "lastName": "Doe",
  "role": "Hotel Admin",
  "associatedHotelId": 5
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/login
Content-Type: {{json}}

{
  "email": "hoteladmin3@localhost.com",
  "password": "P@ssword1"
}


### 11) Admin Confirm Booking
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}/admin/confirm
Authorization: Bearer {{token}}

###

### 12) Admin Cancel Booking
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}/admin/cancel
Authorization: Bearer {{token}}

###

### 13) User Cancel Booking
PUT {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings/{{bookingId}}/cancel
Authorization: Bearer {{token}}

###

### 14) Listing all bookings for a specific hotel
GET {{HotelListing.API_HostAddress}}/api/hotels/{{hotelId}}/bookings
Authorization: Bearer {{token}}
###

